# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "example-tf-state-bucket"
    dynamodb_table = ""
    encrypt        = true
    key            = "dev/us-east-1/logs/terraform.tfstate"
    region         = "us-east-1"
  }
}
