# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-east-1"
  default_tags {
    tags = {
      Environment = "dev"
      Project     = "devops-technical-challenge"
      ManagedBy   = "terragrunt"
    }
  }
}
